### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by eidens-design** [p0lym0rphik/Greenwing#58]
When starting a newly created task, I get an access denied message. I disabled all other plugins and this only ever happens with Greenwing active.

**Comment by jbaubree** [comment]
Hi, i'm sorry to hear that, i do not have enough time to update this repository. I am open for PR.

**Comment by omego** [comment]
@eidens-design See this issue on Kanboard Repo
[https://github.com/kanboard/kanboard/issues/4834](url)
